var vLine ={
    "_1":"美洲",
    "_2":"大洋洲",
    "_3":"歐洲",
    "_4":"亞非",
    "_5":"大陸港澳",
    "_6":"東北亞",
    "_7":"東南亞",
    "_TPE_KLU":"北北基",
    "_TAO_HCU_MLI":"桃竹苗",
    "_TCH_CHA_NTO":"中彰投",
    "_YLI_CYI_TNN":"雲嘉南",
    "_KHH_PIN":"高屏",
    "_YLN_HLN_TTT":"宜花東離島"
}; 
var vCountry ={
    "_1":{
       "_PCT_1":"熱門城市",
       "_PCTZ_1":"熱門區域"
    },
    "_2":{
       "_PCT_2":"熱門城市",
       "_PCTZ_2":"熱門區域"
    },
    "_3":{
       "_PCT_3":"熱門城市",
       "_PCTZ_3":"熱門區域"
    },
    "_4":{
       "_PCT_4":"熱門城市",
       "_PCTZ_4":"熱門區域"
    },
    "_5":{
       "_PCT_5":"熱門城市",
       "_PCTZ_5":"熱門區域"
    },
    "_6":{
       "_PCT_6":"熱門城市",
       "_PCTZ_6":"熱門區域"
    },
    "_7":{
       "_PCT_7":"熱門城市",
       "_PCTZ_7":"熱門區域"
    },
    "_TPE_KLU":{
       "_PCT_TPE_KLU":"熱門城市",
       "_PCTZ_TPE_KLU":"熱門區域",
       "_PCTP_TPE_KLU":"熱門地標"
    },
    "_TAO_HCU_MLI":{
       "_PCT_TAO_HCU_MLI":"熱門城市",
       "_PCTZ_TAO_HCU_MLI":"熱門區域"
    },
    "_TCH_CHA_NTO":{
       "_PCT_TCH_CHA_NTO":"熱門城市",
       "_PCTZ_TCH_CHA_NTO":"熱門區域"
    },
    "_YLI_CYI_TNN":{
       "_PCT_YLI_CYI_TNN":"熱門城市",
       "_PCTZ_YLI_CYI_TNN":"熱門區域"
    },
    "_KHH_PIN":{
       "_PCT_KHH_PIN":"熱門城市",
       "_PCTZ_KHH_PIN":"熱門區域",
       "_PCTP_KHH_PIN":"熱門地標"
    },
    "_YLN_HLN_TTT":{
       "_PCT_YLN_HLN_TTT":"熱門城市",
       "_PCTZ_YLN_HLN_TTT":"熱門區域"
    }
};
var vCity ={
    "_PCT_1":{
       "US_NYC":"紐約-紐約州(NEW YORK NY) NYC-美國",
       "US_LAX":"洛杉磯-加州(LOS ANGELES CA) LAX-美國",
       "US_SFO":"舊金山-加州(SAN FRANCISCO CA) SFO-美國",
       "US_LAS":"拉斯維加斯-內華達州(LAS VEGAS NV) LAS-美國",
       "US_HNL":"壇香山-夏威夷州(HONOLULU) HNL-美國",
       "US_GUM":"關島(GUAM) GUM-美國",
       "CA_YVR":"溫哥華(VANCOUVER) YVR-加拿大",
       "US_BOS":"波士頓-麻塞諸塞州(BOSTON MA) BOS-美國",
       "US_SEA":"西雅圖-華盛頓州(SEATTLE TACOMA) SEA-美國",
       "US_CHI":"芝加哥-伊利諾州(CHICAGO IL) CHI-美國",
       "CA_YYZ":"多倫多(TORONTO) YYZ-加拿大",
       "US_ORL":"奧蘭多-佛州(ORLANDO FL) ORL-美國",
       "US_SAN":"聖地牙哥-加州(SAN DIEGO CA) SAN-美國",
       "US_ANA":"安納漢-加州迪士尼(ANAHEIM CA) ANA-美國",
       "US_SJC":"聖荷西-加州(SAN JOSE CA) SJC-美國",
       "CA_YLL":"露易絲湖(LAKE LOUISE AB) YLL-加拿大",
       "US_WAS":"華盛頓(WASHINGTON DC) WAS-美國",
       "US_MIA":"邁阿密-佛州(MIAMI FL) MIA-美國",
       "US_KOA":"KAILUA KONA-夏威夷州(KAILUA KONA HI) KOA-美國",
       "CA_YBA":"班夫(BANFF) YBA-加拿大"
    },
    "_PCTZ_1":{
       "US_SFO_01":"梅西百貨、聯合廣場-舊金山-加州(SAN FRANCISCO CA) SFO",
       "US_NYC_01":"時代廣場、賓州車站周-紐約-紐約州(NEW YORK NY) NYC",
       "US_GUM_01":"杜夢灣(Tumon)-關島(GUAM) GUM",
       "CA_YVR_01":"市區-溫哥華(VANCOUVER) YVR",
       "US_HNL_01":"檀香山市、威基基海灘-壇香山-夏威夷州(HONOLULU) HNL",
       "US_LAX_06":"洛杉磯機場周圍-洛杉磯-加州(LOS ANGELES CA) LAX",
       "US_NYC_10":"甘迺迪機場、牙買加區-紐約-紐約州(NEW YORK NY) NYC",
       "US_NYC_14":"中央公園、大都會博物-紐約-紐約州(NEW YORK NY) NYC"
    },
    "_PCT_2":{
       "AU_SYD":"雪梨(SYDNEY) SYD-澳洲",
       "AU_MEL":"墨爾本(MELBOURNE) MEL-澳洲",
       "AU_BNE":"布里斯班(BRISBANE) BNE-澳洲",
       "PW_ROR":"帛琉-科羅(KOROR) ROR-帛琉",
       "NZ_AKL":"奧克蘭(AUCKLAND) AKL-紐西蘭",
       "AU_OOL":"黃金海岸(GOLD COAST) OOL-澳洲",
       "AU_CNS":"凱恩斯(CAIRNS) CNS-澳洲",
       "NZ_ZQN":"皇后鎮(QUEENSTOWN) ZQN-紐西蘭",
       "NZ_CHC":"基督城(CHRISTCHURCH) CHC-紐西蘭",
       "US_GUM":"關島(GUAM) GUM-美國",
       "AU_PER":"柏斯(PERTH) PER-澳洲",
       "AU_BMT":"藍山(BLUE MOUNTAIN) BMT-澳洲",
       "FJ_FIJ":"斐濟() FIJ-斐濟",
       "AU_ADL":"阿德雷德(ADELAIDE) ADL-澳洲",
       "NZ_GTN":"庫克山(MT.COOK) GTN-紐西蘭",
       "NZ_TKP":"第卡波(TEKAPO) TKP-紐西蘭",
       "NZ_TPO":"陶波湖(TAUPO) TPO-紐西蘭",
       "AU_DRW":"達爾文(DARWIN) DRW-澳洲",
       "PF_BOB":"BORA BORA-大溪地",
       "NZ_ROT":"羅吐魯阿(ROTOROA) ROT-紐西蘭"
    },
    "_PCTZ_2":{
       "AU_SYD_01":"市中心區-雪梨(SYDNEY) SYD-澳洲",
       "AU_MEL_01":"市中心區-墨爾本(MELBOURNE) MEL-澳洲",
       "AU_SYD_02":"達令港區-雪梨(SYDNEY) SYD-澳洲",
       "AU_BNE_01":"市中心區-布里斯班(BRISBANE) BNE-澳洲",
       "AU_OOL_01":"衝浪者天堂-黃金海岸(GOLD COAST) OOL-澳洲",
       "PW_ROR_01":"帛琉-科羅(KOROR) ROR-帛琉",
       "NZ_AKL_01":"市中心區-奧克蘭(AUCKLAND) AKL-紐西蘭",
       "AU_BNE_02":"南布里斯本-布里斯班(BRISBANE) BNE-澳洲"
    },
    "_PCT_3":{
       "UK_LON":"倫敦(LONDON) LON-英國",
       "FR_PAR":"巴黎(PARIS) PAR-法國",
       "DE_MUC":"慕尼黑-德國",
       "NL_AMS":"阿姆斯特丹(AMSTERDAM) AMS-荷蘭",
       "DE_FRA":"法蘭克福(FRANKFURT) FRA-德國",
       "AT_VIE":"維也納(VIENNA) VIE-奧地利",
       "CZ_PRG":"布拉格(PRAGUE) PRG-捷克",
       "IT_MIL":"米蘭(MILAN) MIL-義大利",
       "DE_BER":"柏林(BERLIN) BER-德國",
       "IT_ROM":"羅馬(ROME) ROM-義大利",
       "ES_BCN":"巴塞隆納(BARCELONA) BCN-西班牙",
       "DE_CGN":"科隆(COLOGNE) CGN-德國",
       "ES_MAD":"馬德里(MADRID) MAD-西班牙",
       "SE_STO":"斯德哥爾摩(STOCKHOLM) STO-瑞典",
       "IT_VCE":"威尼斯(VENICE) VCE-義大利",
       "DE_DUS":"杜塞道夫(DUSSELDORF) DUS-德國",
       "DE_DRS":"德勒斯登(DRESDEN) DRS-德國",
       "AT_SZG":"薩爾斯堡(SALZBURG) SZG-奧地利",
       "GR_ATH":"雅典(ATHENS) ATH-希臘",
       "RU_MOW":"莫斯科(MOSCOW) MOW-俄羅斯"
    },
    "_PCTZ_3":{
       "DE_MUC_06":"中央車站-慕尼黑(MUNICH) MUC-德國",
       "FR_PAR_01":"1區◆羅浮宮、杜勒麗-巴黎(PARIS) PAR-法國",
       "FR_PAR_10":"10區◆巴黎北站-巴黎(PARIS) PAR-法國",
       "UK_LON_02":"帕丁頓-倫敦(LONDON) LON-英國",
       "CZ_PRG_01":"1區◆舊城區-布拉格-捷克",
       "FR_PAR_08":"8區◆香榭大道-巴黎(PARIS) PAR-法國",
       "DE_DRS_04":"中央車站-德勒斯登(DRESDEN) DRS-德國",
       "FR_PAR_09":"9區◆歌劇院區-巴黎(PARIS) PAR-法國"
    },
    "_PCT_4":{
       "AE_DXB":"杜拜(DUBAI) DXB-阿拉伯聯合大公國",
       "MV_MDV":"馬爾地夫() MDV-馬爾地夫",
       "IN_DEL":"德里(DELHI) DEL-印度",
       "TR_IST":"伊斯坦堡(ISTANBUL) IST-土耳其",
       "IN_BOM":"孟買(MUMBAI(BOMBAY)) BOM-印度",
       "MV_MLE":"馬列(MALE) MLE-馬爾地夫",
       "AE_AUH":"阿布達比(ABU DHABI) AUH-阿拉伯聯合大公國",
       "LK_CMB":"可倫坡(COLOMBO) CMB-斯里蘭卡",
       "IL_ETH":"EILAT() ETH-以色列",
       "IN_BLR":"BANGALORE() BLR-印度",
       "MU_MRU":"模里西斯(MAURITIUS) MRU-模里西斯",
       "NP_KTM":"加德滿都(KATHMANDU) KTM-尼泊爾",
       "EG_CAI":"開羅(CAIRO) CAI-埃及",
       "TR_ANK":"安卡拉(ANKARA) ANK-土耳其",
       "ZA_CPT":"開普敦(CAPE TOWN) CPT-南非",
       "KE_NBO":"奈洛比(NAIROBI) NBO-肯亞",
       "TR_KUS":"庫薩達西(KUSADASI KUSADASI) KUS-土耳其",
       "MA_RAK":"馬拉喀什(MARRAKECH) RAK-摩洛哥",
       "ZA_JNB":"約翰尼斯堡(JOHANNESBURG) JNB-南非",
       "IN_JAI":"捷普(JAIPUR) JAI-印度"
    },
    "_PCTZ_4":{
		"MV_MDV_01":"馬列-馬爾地夫() MDV-馬爾地夫",
		"AE_DXB_01":"市區-杜拜(DUBAI) DXB-阿拉伯聯合大公國",
		"IN_DEL_01":"新城-德里(DELHI) DEL-印度",
		"AE_DXB_02":"海灘區-杜拜(DUBAI) DXB-阿拉伯聯合大公國",
		"MV_MDV_02":"北馬列環礁-馬爾地夫() MDV-馬爾地夫",
		"AE_DXB_03":"柏迪拜-杜拜(DUBAI) DXB-阿拉伯聯合大公國",
		"IN_BLR_01":"市中心-BANGALORE() BLR-印度",
		"TR_IST_01":"老城區-伊斯坦堡(ISTANBUL) IST-土耳其"
    },
    "_PCT_5":{
		"CN_HKG":"香港(HONG KONG) HKG-中國大陸",
		"CN_MFM":"澳門(MACAU) MFM-中國大陸",
		"CN_SHA":"上海(SHANGHAI) SHA-中國大陸",
		"CN_PEK":"北京(BEIJING) PEK-中國大陸",
		"CN_ZUH":"珠海-廣東省(ZHUHAI) ZUH-中國大陸",
		"CN_XMN":"廈門-福建省(XIAMEN) XMN-中國大陸",
		"CN_HGH":"杭州-浙江省(HANGZHOU) HGH-中國大陸",
		"CN_SZX":"深圳-廣東省(SHENZHEN) SZX-中國大陸",
		"CN_CAN":"廣州-廣東省(GUANGZHOU) CAN-中國大陸",
		"CN_SUZ":"蘇州-江蘇省(SUZHOU) SUZ-中國大陸",
		"CN_SYX":"三亞-海南省(SANYA) SYX-中國大陸",
		"CN_NKG":"南京-江蘇省(NANJING) NKG-中國大陸",
		"CN_CTU":"成都-四川省(CHENGDU) CTU-中國大陸",
		"CN_FOC":"福州-福建省(FUZHOU) FOC-中國大陸",
		"CN_SIA":"西安-陜西省(XIAN) SIA-中國大陸",
		"CN_TAO":"青島-山東省(QINGDAO) TAO-中國大陸",
		"CN_WUH":"武漢-湖北省(WUHAN) WUH-中國大陸",
		"CN_TSN":"天津-河北省(TIANJIN) TSN-中國大陸",
		"CN_NGB":"寧波-浙江省(NINGBO) NGB-中國大陸",
		"CN_KMG":"昆明-雲南省(KUNMING) KMG-中國大陸"
    },
    "_PCTZ_5":{
		"CN_HKG_18":"尖沙咀-香港(HONG KONG) HKG-中國大陸",
		"CN_MFM_09":"路氹-澳門(MACAU) MFM-中國大陸",
		"CN_HKG_05":"銅鑼灣-香港(HONG KONG) HKG-中國大陸",
		"CN_HKG_02":"中環/金鐘-香港(HONG KONG) HKG-中國大陸",
		"CN_HKG_17":"佐敦-香港(HONG KONG) HKG-中國大陸",
		"CN_HKG_08":"西環/上環-香港(HONG KONG) HKG-中國大陸",
		"CN_HKG_15":"旺角/太子-香港(HONG KONG) HKG-中國大陸",
		"CN_HKG_04":"灣仔-香港(HONG KONG) HKG-中國大陸"
    },
    "_PCT_6":{
		"JP_TYO":"東京(TOKYO) TYO-日本",
		"JP_OSA":"大阪(OSAKA) OSA-日本",
		"JP_OKA":"沖繩(OKINAWA) OKA-日本",
		"KR_SEL":"首爾(SEOUL) SEL-韓國",
		"JP_KYO":"京都(KYOTO) KYO-日本",
		"JP_FUK":"福岡市-福岡縣(FUKUOKA) FUK-日本",
		"JP_SPK":"札幌-北海道(SAPPORO) SPK-日本",
		"JP_NGO":"名古屋-愛知縣(NAGOYA) NGO-日本",
		"JP_KAL":"輕井澤-長野縣(KARUIZAWA) KAL-日本",
		"JP_HKD":"函館-北海道(HAKODATE) HKD-日本",
		"KR_PUS":"釜山(PUSAN) PUS-韓國",
		"JP_KOB":"神戶市-兵庫縣(KOBE) KOB-日本",
		"JP_JHA":"箱根-神奈川縣(HAKONE) JHA-日本",
		"JP_FUC":"河口湖-山梨縣(KAWAGUCHIKO) FUC-日本",
		"JP_YOK":"橫濱-神奈川縣(YOKOHAMA) YOK-日本",
		"JP_NOB":"登別-北海道(NOBORIBETSU) NOB-日本",
		"KR_ICN":"仁川(INCHEON) ICN-韓國",
		"JP_KZA":"金澤市-石川縣(KANAZAWA) KZA-日本",
		"JP_TJH":"洞爺湖-北海道(TOYAKO) TJH-日本",
		"JP_HIJ":"廣島市-廣島縣(HIROSHIMA SHI) HIJ-日本"
    },
    "_PCTZ_6":{
		"JP_TYO_04":"新宿-東京(TOKYO) TYO-日本",
		"JP_OSA_08":"道頓堀、難波-大阪(OSAKA) OSA-日本",
		"JP_TYO_24":"上野御徒町-東京(TOKYO) TYO-日本",
		"JP_TYO_20":"東京-東京(TOKYO) TYO-日本",
		"JP_TYO_10":"淺草-東京(TOKYO) TYO-日本",
		"JP_OKA_01":"那霸地區-沖繩(OKINAWA) OKA-日本",
		"JP_OSA_06":"心齋橋-大阪(OSAKA) OSA-日本",
		"JP_TYO_05":"池袋-東京(TOKYO) TYO-日本"
    },
    "_PCT_7":{
		"SG_SIN":"新加坡(SINGAPORE) SIN-新加坡",
		"TH_BKK":"曼谷(BANGKOK) BKK-泰國",
		"ID_DPS":"峇里島(BALI) DPS-印尼",
		"TH_HHQ":"華欣(HUA-HIN) HHQ-泰國",
		"MY_KUL":"吉隆坡(Kuala Lumpur) KUL-馬來西亞",
		"TH_PYX":"芭達雅(PATTAYA) PYX-泰國",
		"TH_USM":"蘇美島(KOH SAMUI) USM-泰國",
		"MY_BKI":"沙巴(亞庇)(SABAH（KOTA KINABALU）) BKI-馬來西亞",
		"VN_SGN":"胡志明市(HO CHI MINH) SGN-越南",
		"PH_MNL":"馬尼拉(MANILA) MNL-菲律賓",
		"PH_CEB":"宿霧(CEBU) CEB-菲律賓",
		"PH_BOR":"長灘島(BORACAY) BOR-菲律賓",
		"TH_CNX":"清邁(CHIANG MAI) CNX-泰國",
		"TH_HKT":"普吉島(PHUKET) HKT-泰國",
		"SG_SEN":"SENTOSA(聖陶沙) SEN-新加坡",
		"VN_HAN":"河內(HANOI) HAN-越南",
		"ID_JKT":"雅加達(JAKARTA) JKT-印尼",
		"MY_JHB":"柔佛州(新山)(JOHOR BAHRU) JHB-馬來西亞",
		"MY_PEN":"檳城(PENANG) PEN-馬來西亞",
		"PH_BOH":"薄荷島(BOHOL) BOH-菲律賓"
    },
    "_PCTZ_7":{
		"TH_BKK_11":"蘇坤逸區-曼谷(BANGKOK) BKK-泰國",
		"SG_SIN_10":"濱海行政區-新加坡(SINGAPORE) SIN-新加坡",
		"TH_BKK_03":"四面佛鬧區-曼谷(BANGKOK) BKK-泰國",
		"SG_SIN_15":"烏節路地區-新加坡(SINGAPORE) SIN-新加坡",
		"SG_SIN_12":"牛車水地區-新加坡(SINGAPORE) SIN-新加坡",
		"SG_SIN_09":"聖陶沙地區-新加坡(SINGAPORE) SIN-新加坡",
		"TH_BKK_10":"湄南河畔區-曼谷(BANGKOK) BKK-泰國",
		"TH_BKK_14":"席隆區-曼谷(BANGKOK) BKK-泰國"
    },
    "_PCT_TPE_KLU":{
		"TW_TPE":"台北",
		"TW_KLU":"基隆",
		"TW_PAN":"新北",
		"TW_TPE_TWTPE001":"北投區-台北",
		"TW_TPE_TWTPE004":"中山區-台北",
		"TW_PAN_TWPAN016":"淡水區-新北",
		"TW_PAN_TWPAN017":"萬里區-新北",
		"TW_TPE_TWTPE011":"大安區-台北",
		"TW_TPE_TWTPE009":"信義區-台北",
		"TW_TPE_TWTPE010":"中正區-台北",
		"TW_PAN_TWPAN015":"金山區-新北",
		"TW_TPE_TWTPE005":"松山區-台北",
		"TW_TPE_TWTPE002":"士林區-台北",
		"TW_PAN_TWPAN041":"烏來區-新北",
		"TW_PAN_TWPAN023":"貢寮區-新北",
		"TW_PAN_TWPAN031":"板橋區-新北",
		"TW_PAN_TWPAN040":"三峽區-新北",
		"TW_TPE_TWTPE006":"大同區-台北",
		"TW_TPE_TWTPE008":"萬華區-台北",
		"TW_TPE_TWTPE003":"內湖區-台北",
		"TW_KLU_TWKLU001":"中正區-基隆"
    },
    "_PCTZ_TPE_KLU":{
		"TW_TPE_TWTPE014":"北投溫泉-台北",
		"TW_TPE_TWTPE003":"台北車站-台北",
		"TW_TPE_TWTPE001":"西門町商圈-台北",
		"TW_TPE_TWTPE013":"大直美麗華-台北",
		"TW_PAN_TWPAN016":"碧潭風景區-新北",
		"TW_TPE_TWTPE007":"士林天母商圈-台北",
		"TW_TPE_TWTPE012":"小巨蛋商圈-台北",
		"TW_TPE_TWTPE005":"忠孝sogo商圈-台北"
    },
    "_PCTP_TPE_KLU":{
		"TW_TPE_TWTPES59":"【淡水信義線】新北投捷運站-台北",
		"TW_PAN_TWPANS01":"【淡水信義線】淡水捷運站-新北",
		"TW_TPE_TWTPES43":"【文湖線】木柵捷運站-台北",
		"TW_TPE_TWTPEA03":"【淡水信義線】台北101/世貿站-台北",
		"TW_PAN_TWPANS91":"【板南線】板橋捷運站-新北",
		"TW_TPE_TWTPES72":"【淡水信義線】台北車站-台北",
		"TW_TPE_TWTPES71":"【文湖線】松山機場捷運站-台北",
		"TW_PAN_TWPANS02":"【淡水信義線】紅樹林捷運站-新北"
    },
    "_PCT_TAO_HCU_MLI":{
		"TW_HCU":"新竹",
		"TW_TAO":"桃園",
		"TW_MLI":"苗栗",
		"TW_MLI_TWMLI018":"泰安鄉-苗栗",
		"TW_TAO_TWTAO006":"中壢區-桃園",
		"TW_TAO_TWTAO002":"大園區-桃園",
		"TW_TAO_TWTAO011":"大溪區-桃園",
		"TW_HCU_TWHCU008":"關西鎮-新竹",
		"TW_TAO_TWTAO005":"桃園區-桃園",
		"TW_HCU_TWHCU001":"北區-新竹",
		"TW_HCU_TWHCU012":"尖石鄉-新竹",
		"TW_MLI_TWMLI010":"頭份鎮-苗栗",
		"TW_HCU_TWHCU003":"東區-新竹",
		"TW_MLI_TWMLI014":"南庄鄉-苗栗",
		"TW_MLI_TWMLI009":"竹南鎮-苗栗",
		"TW_HCU_TWHCU007":"竹北市-新竹",
		"TW_HCU_TWHCU016":"五峰鄉-新竹",
		"TW_MLI_TWMLI008":"三義鄉-苗栗",
		"TW_TAO_TWTAO012":"龍潭區-桃園",
		"TW_TAO_TWTAO013":"復興區-桃園"
    },
    "_PCTZ_TAO_HCU_MLI":{
		"TW_HCU_TWHCU006":"雪霸‧觀霧-新竹",
		"TW_HCU_TWHCU005":"關西‧六福村-新竹",
		"TW_MLI_TWMLI006":"泰安溫泉-苗栗",
		"TW_TAO_TWTAO001":"桃園國際機場-桃園",
		"TW_HCU_TWHCU003":"青草湖-新竹",
		"TW_TAO_TWTAO007":"石門水庫-桃園",
		"TW_TAO_TWTAO002":"中壢火車站-桃園",
		"TW_TAO_TWTAO006":"桃園火車站-桃園"
    },
    "_PCT_TCH_CHA_NTO":{
		"TW_NTO":"南投",
		"TW_TCH":"台中",
		"TW_CHA":"彰化",
		"TW_TCH_TWTCH007":"西屯區-台中",
		"TW_NTO_TWNTO008":"仁愛鄉-南投",
		"TW_NTO_TWNTO007":"魚池鄉-南投",
		"TW_TCH_TWTCH001":"中區-台中",
		"TW_NTO_TWNTO005":"埔里鎮-南投",
		"TW_TCH_TWTCH004":"西區-台中",
		"TW_NTO_TWNTO013":"鹿谷鄉-南投",
		"TW_CHA_TWCHA002":"員林鎮-彰化",
		"TW_TCH_TWTCH014":"后里區-台中",
		"TW_TCH_TWTCH006":"北屯區-台中",
		"TW_TCH_TWTCH021":"和平區-台中",
		"TW_TCH_TWTCH005":"北區-台中",
		"TW_CHA_TWCHA001":"彰化市-彰化",
		"TW_CHA_TWCHA004":"鹿港鎮-彰化",
		"TW_TCH_TWTCH008":"南屯區-台中",
		"TW_NTO_TWNTO012":"竹山鎮-南投",
		"TW_NTO_TWNTO010":"集集鎮-南投"
    },
    "_PCTZ_TCH_CHA_NTO":{
		"TW_NTO_TWNTO001":"清境農場-南投",
		"TW_NTO_TWNTO003":"日月潭-南投",
		"TW_NTO_TWNTO004":"溪頭‧杉林溪-南投",
		"TW_NTO_TWNTO002":"日月潭依達邵-南投",
		"TW_TCH_TWTCH001":"逢甲商圈-台中",
		"TW_TCH_TWTCH006":"谷關溫泉-台中",
		"TW_TCH_TWTCH004":"武陵農場-台中",
		"TW_TCH_TWTCH005":"梨山福壽山-台中"
    },
    "_PCT_YLI_CYI_TNN":{
		"TW_YLI":"雲林",
		"TW_CYI":"嘉義",
		"TW_TNN":"台南",
		"TW_TNN_TWTNN001":"中西區-台南",
		"TW_CYI_TWCYI002":"西區-嘉義",
		"TW_TNN_TWTNN002":"東區-台南",
		"TW_TNN_TWTNN005":"安平區-台南",
		"TW_TNN_TWTNN004":"北區-台南",
		"TW_CYI_TWCYI001":"東區-嘉義",
		"TW_YLI_TWYLI001":"斗六市-雲林",
		"TW_YLI_TWYLI004":"古坑鄉-雲林",
		"TW_TNN_TWTNN027":"白河區-台南",
		"TW_TNN_TWTNN003":"南區-台南",
		"TW_TNN_TWTNN007":"永康區-台南",
		"TW_CYI_TWCYI016":"竹崎鄉-嘉義",
		"TW_CYI_TWCYI015":"中埔鄉-嘉義",
		"TW_CYI_TWCYI021":"番路鄉-嘉義",
		"TW_CYI_TWCYI007":"民雄鄉-嘉義",
		"TW_CYI_TWCYI017":"梅山鄉-嘉義"
    },
    "_PCTZ_YLI_CYI_TNN":{
		"TW_CYI_TWCYI004":"阿里山-嘉義",
		"TW_TNN_TWTNN004":"關子嶺-台南",
		"TW_YLI_TWYLI003":"劍湖山-雲林",
		"TW_TNN_TWTNN011":"花園夜市-台南",
		"TW_CYI_TWCYI002":"中正公園商圈-嘉義",
		"TW_TNN_TWTNN003":"府城商圈-台南",
		"TW_TNN_TWTNN009":"赤崁樓-台南",
		"TW_TNN_TWTNN001":"安平商圈-台南"
    },
    "_PCT_KHH_PIN":{
		"TW_KHH":"高雄",
		"TW_PIN":"屏東",
		"TW_KHH_TWKHH015":"大樹區-高雄",
		"TW_KHH_TWKHH001":"鹽埕區-高雄",
		"TW_KHH_TWKHH005":"三民區-高雄",
		"TW_KHH_TWKHH008":"苓雅區-高雄",
		"TW_KHH_TWKHH003":"左營區-高雄",
		"TW_KHH_TWKHH006":"新興區-高雄",
		"TW_KHH_TWKHH007":"前金區-高雄",
		"TW_KHH_TWKHH002":"鼓山區-高雄",
		"TW_PIN_TWPIN001":"屏東市-屏東",
		"TW_KHH_TWKHH009":"前鎮區-高雄",
		"TW_PIN_TWPIN029":"琉球鄉-屏東",
		"TW_PIN_TWPIN031":"車城鄉-屏東",
		"TW_PIN_TWPIN023":"東港鎮-屏東",
		"TW_KHH_TWKHH012":"鳳山區-高雄",
		"TW_PIN_TWPIN033":"牡丹鄉-屏東",
		"TW_KHH_TWKHH032":"六龜區-高雄",
		"TW_KHH_TWKHH022":"田寮區-高雄"
    },
    "_PCTZ_KHH_PIN":{
		"TW_PIN_TWPIN001":"墾丁大街-屏東",
		"TW_PIN_TWPIN014":"墾丁白砂-屏東",
		"TW_PIN_TWPIN015":"小琉球-屏東",
		"TW_KHH_TWKHH014":"義大世界-高雄",
		"TW_PIN_TWPIN002":"南灣-屏東",
		"TW_KHH_TWKHH013":"六合美麗島-高雄",
		"TW_PIN_TWPIN010":"四重溪-屏東",
		"TW_KHH_TWKHH016":"三多商圈-高雄"
    },
    "_PCTP_KHH_PIN":{
		"TW_KHH_TWKHHS33":"【橘線】鳳山西站(高雄市議會)捷運站-高雄",
		"TW_KHH_TWKHHS10":"【紅線】高雄車站捷運站-高雄",
		"TW_KHH_TWKHHS01":"【紅線】小港(小港醫院)捷運站-高雄",
		"TW_KHH_TWKHHS13":"【紅線】巨蛋(三民家商)捷運站-高雄",
		"TW_KHH_TWKHHS09":"【紅線】美麗島捷運站-高雄",
		"TW_KHH_TWKHHS02":"【紅線】高雄國際機場捷運站-高雄",
		"TW_KHH_TWKHHS15":"【紅線】左營(高鐵)捷運站-高雄",
		"TW_KHH_TWKHHS25":"【橘線】西子灣(哈瑪星)捷運站-高雄"
    },
    "_PCT_YLN_HLN_TTT":{
		"TW_YLN":"宜蘭",
		"TW_HLN":"花蓮",
		"TW_TTT":"台東",
		"TW_KNH":"金門",
		"TW_MFK":"馬祖",
		"TW_TTT_TWTTT001":"臺東市-台東",
		"TW_MZG_TWMZG001":"馬公市-澎湖",
		"TW_YLN_TWYLN006":"羅東鎮-宜蘭",
		"TW_YLN_TWYLN001":"宜蘭市-宜蘭",
		"TW_HLN_TWHLN004":"壽豐鄉-花蓮",
		"TW_TTT_TWTTT007":"池上鄉-台東",
		"TW_YLN_TWYLN011":"蘇澳鎮-宜蘭",
		"TW_TTT_TWTTT011":"綠島鄉-台東",
		"TW_TTT_TWTTT008":"鹿野鄉-台東",
		"TW_YLN_TWYLN002":"頭城鎮-宜蘭",
		"TW_YLN_TWYLN010":"大同鄉-宜蘭",
		"TW_TTT_TWTTT010":"卑南鄉-台東"
    },
    "_PCTZ_YLN_HLN_TTT":{
       "TW_TTT_TWTTT001":"知本溫泉-台東",
       "TW_YLN_TWYLN001":"礁溪溫泉-宜蘭",
       "TW_YLN_TWYLN008":"明池棲蘭-宜蘭",
       "TW_HLN_TWHLN001":"太魯閣-花蓮",
       "TW_YLN_TWYLN006":"羅東夜市-宜蘭",
       "TW_HLN_TWHLN004":"海洋公園-花蓮",
       "TW_MZG_TWMZG001":"馬公市區-澎湖",
       "TW_TTT_TWTTT002":"綠島-台東"
    }
};